export const sampleProducts = [
  // 📱 SMARTPHONES
  {
    product_category: "smartphones",
    product_name: "Apple iPhone 15",
    product_brand: "Apple",
    product_cost_price: 65000,
    product_tax: 18,
    product_selling_price: 78000,
    product_quantity: 50,
    product_min_quantity: 5,
    product_sku: "SP-IP15-001",
  },
  {
    product_category: "smartphones",
    product_name: "Samsung Galaxy S23",
    product_brand: "Samsung",
    product_cost_price: 55000,
    product_tax: 18,
    product_selling_price: 69000,
    product_quantity: 40,
    product_min_quantity: 5,
    product_sku: "SP-S23-002",
  },
  {
    product_category: "smartphones",
    product_name: "OnePlus 12",
    product_brand: "OnePlus",
    product_cost_price: 48000,
    product_tax: 18,
    product_selling_price: 57999,
    product_quantity: 35,
    product_min_quantity: 5,
    product_sku: "SP-OP12-003",
  },
  {
    product_category: "smartphones",
    product_name: "Redmi Note 13 Pro",
    product_brand: "Xiaomi",
    product_cost_price: 21000,
    product_tax: 18,
    product_selling_price: 25999,
    product_quantity: 60,
    product_min_quantity: 8,
    product_sku: "SP-RN13-004",
  },
  {
    product_category: "smartphones",
    product_name: "Vivo V30",
    product_brand: "Vivo",
    product_cost_price: 27000,
    product_tax: 18,
    product_selling_price: 32999,
    product_quantity: 45,
    product_min_quantity: 6,
    product_sku: "SP-V30-005",
  },
  {
    product_category: "smartphones",
    product_name: "Realme GT 6",
    product_brand: "Realme",
    product_cost_price: 24000,
    product_tax: 18,
    product_selling_price: 29999,
    product_quantity: 55,
    product_min_quantity: 7,
    product_sku: "SP-GT6-006",
  },

  // 📺 TV
  {
    product_category: "TV",
    product_name: "Samsung 55 Inch QLED",
    product_brand: "Samsung",
    product_cost_price: 52000,
    product_tax: 18,
    product_selling_price: 64999,
    product_quantity: 20,
    product_min_quantity: 3,
    product_sku: "TV-SAM-007",
  },
  {
    product_category: "TV",
    product_name: "LG 43 Inch Smart TV",
    product_brand: "LG",
    product_cost_price: 28000,
    product_tax: 18,
    product_selling_price: 35999,
    product_quantity: 25,
    product_min_quantity: 3,
    product_sku: "TV-LG-008",
  },
  {
    product_category: "TV",
    product_name: "Sony Bravia 65 Inch",
    product_brand: "Sony",
    product_cost_price: 88000,
    product_tax: 18,
    product_selling_price: 109999,
    product_quantity: 10,
    product_min_quantity: 2,
    product_sku: "TV-SONY-009",
  },
  {
    product_category: "TV",
    product_name: "Mi 50 Inch 4K TV",
    product_brand: "Xiaomi",
    product_cost_price: 32000,
    product_tax: 18,
    product_selling_price: 39999,
    product_quantity: 30,
    product_min_quantity: 4,
    product_sku: "TV-MI-010",
  },

  // ❄️ REFRIGERATORS
  {
    product_category: "Refrigerators",
    product_name: "LG 260L Double Door",
    product_brand: "LG",
    product_cost_price: 24000,
    product_tax: 18,
    product_selling_price: 28999,
    product_quantity: 15,
    product_min_quantity: 2,
    product_sku: "RF-LG-011",
  },
  {
    product_category: "Refrigerators",
    product_name: "Samsung 253L Frost Free",
    product_brand: "Samsung",
    product_cost_price: 23000,
    product_tax: 18,
    product_selling_price: 27999,
    product_quantity: 18,
    product_min_quantity: 2,
    product_sku: "RF-SAM-012",
  },
  {
    product_category: "Refrigerators",
    product_name: "Whirlpool 265L",
    product_brand: "Whirlpool",
    product_cost_price: 21000,
    product_tax: 18,
    product_selling_price: 25999,
    product_quantity: 20,
    product_min_quantity: 2,
    product_sku: "RF-WH-013",
  },

  // ❄️ AC
  {
    product_category: "AC",
    product_name: "LG 1.5 Ton 5 Star AC",
    product_brand: "LG",
    product_cost_price: 36000,
    product_tax: 18,
    product_selling_price: 42999,
    product_quantity: 12,
    product_min_quantity: 2,
    product_sku: "AC-LG-014",
  },
  {
    product_category: "AC",
    product_name: "Daikin 1.5 Ton Inverter AC",
    product_brand: "Daikin",
    product_cost_price: 38000,
    product_tax: 18,
    product_selling_price: 45999,
    product_quantity: 10,
    product_min_quantity: 2,
    product_sku: "AC-DAI-015",
  },
  {
    product_category: "AC",
    product_name: "Voltas 1 Ton Split AC",
    product_brand: "Voltas",
    product_cost_price: 29000,
    product_tax: 18,
    product_selling_price: 34999,
    product_quantity: 14,
    product_min_quantity: 2,
    product_sku: "AC-VOL-016",
  },

  // 💻 COMPUTERS
  {
    product_category: "Computers",
    product_name: "Dell Inspiron 15",
    product_brand: "Dell",
    product_cost_price: 52000,
    product_tax: 18,
    product_selling_price: 62999,
    product_quantity: 18,
    product_min_quantity: 3,
    product_sku: "PC-DEL-017",
  },
  {
    product_category: "Computers",
    product_name: "HP Pavilion 14",
    product_brand: "HP",
    product_cost_price: 54000,
    product_tax: 18,
    product_selling_price: 65999,
    product_quantity: 16,
    product_min_quantity: 3,
    product_sku: "PC-HP-018",
  },
  {
    product_category: "Computers",
    product_name: "Apple MacBook Air M2",
    product_brand: "Apple",
    product_cost_price: 95000,
    product_tax: 18,
    product_selling_price: 114999,
    product_quantity: 8,
    product_min_quantity: 2,
    product_sku: "PC-MAC-019",
  },
  {
    product_category: "Computers",
    product_name: "Lenovo IdeaPad Slim 5",
    product_brand: "Lenovo",
    product_cost_price: 48000,
    product_tax: 18,
    product_selling_price: 58999,
    product_quantity: 20,
    product_min_quantity: 3,
    product_sku: "PC-LEN-020",
  },
];
