import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import Product from "../models/product.models.js";
import connectDB from "../db/index.db.js";

// Get current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env from backend root directory
dotenv.config({ path: path.join(__dirname, "..", ".env") });

const products = [
    // Electronics - Smartphones
    {
        product_category: "Electronics",
        product_sub_category: "Smartphones",
        product_name: "Apple iPhone 15 Pro",
        product_brand: "Apple",
        product_category_lower: "electronics",
        product_sub_category_lower: "smartphones",
        product_brand_lower: "apple",
        product_name_lower: "apple iphone 15 pro",
        product_image: "https://images.unsplash.com/photo-1592286927505-2fd8fcbf8a57?w=400",
        product_cost_price: 95000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 129900,
        product_quantity: 25,
        product_min_quantity: 5,
        product_sku: "ELE-SMT-APP-001",
        is_active: true,
    },
    {
        product_category: "Electronics",
        product_sub_category: "Smartphones",
        product_name: "Samsung Galaxy S24 Ultra",
        product_brand: "Samsung",
        product_category_lower: "electronics",
        product_sub_category_lower: "smartphones",
        product_brand_lower: "samsung",
        product_name_lower: "samsung galaxy s24 ultra",
        product_image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400",
        product_cost_price: 85000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 124999,
        product_quantity: 30,
        product_min_quantity: 5,
        product_sku: "ELE-SMT-SAM-001",
        is_active: true,
    },
    {
        product_category: "Electronics",
        product_sub_category: "Smartphones",
        product_name: "OnePlus 12",
        product_brand: "OnePlus",
        product_category_lower: "electronics",
        product_sub_category_lower: "smartphones",
        product_brand_lower: "oneplus",
        product_name_lower: "oneplus 12",
        product_image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
        product_cost_price: 45000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 64999,
        product_quantity: 40,
        product_min_quantity: 10,
        product_sku: "ELE-SMT-ONE-001",
        is_active: true,
    },
    {
        product_category: "Electronics",
        product_sub_category: "Smartphones",
        product_name: "Google Pixel 8 Pro",
        product_brand: "Google",
        product_category_lower: "electronics",
        product_sub_category_lower: "smartphones",
        product_brand_lower: "google",
        product_name_lower: "google pixel 8 pro",
        product_image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400",
        product_cost_price: 70000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 106999,
        product_quantity: 3,
        product_min_quantity: 5,
        product_sku: "ELE-SMT-GOO-001",
        is_active: true,
    },

    // Electronics - Laptops
    {
        product_category: "Electronics",
        product_sub_category: "Laptops",
        product_name: "MacBook Pro 14-inch M3",
        product_brand: "Apple",
        product_category_lower: "electronics",
        product_sub_category_lower: "laptops",
        product_brand_lower: "apple",
        product_name_lower: "macbook pro 14-inch m3",
        product_image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca4?w=400",
        product_cost_price: 150000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 199900,
        product_quantity: 15,
        product_min_quantity: 5,
        product_sku: "ELE-LAP-APP-001",
        is_active: true,
    },
    {
        product_category: "Electronics",
        product_sub_category: "Laptops",
        product_name: "Dell XPS 15",
        product_brand: "Dell",
        product_category_lower: "electronics",
        product_sub_category_lower: "laptops",
        product_brand_lower: "dell",
        product_name_lower: "dell xps 15",
        product_image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400",
        product_cost_price: 120000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 164990,
        product_quantity: 20,
        product_min_quantity: 5,
        product_sku: "ELE-LAP-DEL-001",
        is_active: true,
    },
    {
        product_category: "Electronics",
        product_sub_category: "Laptops",
        product_name: "HP Pavilion Gaming",
        product_brand: "HP",
        product_category_lower: "electronics",
        product_sub_category_lower: "laptops",
        product_brand_lower: "hp",
        product_name_lower: "hp pavilion gaming",
        product_image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400",
        product_cost_price: 55000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 74990,
        product_quantity: 12,
        product_min_quantity: 8,
        product_sku: "ELE-LAP-HP-001",
        is_active: true,
    },

    // Electronics - Headphones
    {
        product_category: "Electronics",
        product_sub_category: "Headphones",
        product_name: "AirPods Pro 2nd Gen",
        product_brand: "Apple",
        product_category_lower: "electronics",
        product_sub_category_lower: "headphones",
        product_brand_lower: "apple",
        product_name_lower: "airpods pro 2nd gen",
        product_image: "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400",
        product_cost_price: 18000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 26900,
        product_quantity: 50,
        product_min_quantity: 10,
        product_sku: "ELE-HDP-APP-001",
        is_active: true,
    },
    {
        product_category: "Electronics",
        product_sub_category: "Headphones",
        product_name: "Sony WH-1000XM5",
        product_brand: "Sony",
        product_category_lower: "electronics",
        product_sub_category_lower: "headphones",
        product_brand_lower: "sony",
        product_name_lower: "sony wh-1000xm5",
        product_image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400",
        product_cost_price: 22000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 29990,
        product_quantity: 35,
        product_min_quantity: 10,
        product_sku: "ELE-HDP-SON-001",
        is_active: true,
    },
    {
        product_category: "Electronics",
        product_sub_category: "Headphones",
        product_name: "JBL Tune 770NC",
        product_brand: "JBL",
        product_category_lower: "electronics",
        product_sub_category_lower: "headphones",
        product_brand_lower: "jbl",
        product_name_lower: "jbl tune 770nc",
        product_image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
        product_cost_price: 4500,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 6999,
        product_quantity: 60,
        product_min_quantity: 15,
        product_sku: "ELE-HDP-JBL-001",
        is_active: true,
    },

    // Clothing - Men's Wear
    {
        product_category: "Clothing",
        product_sub_category: "Men's Wear",
        product_name: "Levi's 501 Original Jeans",
        product_brand: "Levi's",
        product_category_lower: "clothing",
        product_sub_category_lower: "men's wear",
        product_brand_lower: "levi's",
        product_name_lower: "levi's 501 original jeans",
        product_image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
        product_cost_price: 2500,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 3999,
        product_quantity: 80,
        product_min_quantity: 20,
        product_sku: "CLO-MEN-LEV-001",
        is_active: true,
    },
    {
        product_category: "Clothing",
        product_sub_category: "Men's Wear",
        product_name: "Nike Sportswear T-Shirt",
        product_brand: "Nike",
        product_category_lower: "clothing",
        product_sub_category_lower: "men's wear",
        product_brand_lower: "nike",
        product_name_lower: "nike sportswear t-shirt",
        product_image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
        product_cost_price: 800,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 1499,
        product_quantity: 120,
        product_min_quantity: 30,
        product_sku: "CLO-MEN-NIK-001",
        is_active: true,
    },
    {
        product_category: "Clothing",
        product_sub_category: "Men's Wear",
        product_name: "Adidas Hoodie",
        product_brand: "Adidas",
        product_category_lower: "clothing",
        product_sub_category_lower: "men's wear",
        product_brand_lower: "adidas",
        product_name_lower: "adidas hoodie",
        product_image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400",
        product_cost_price: 1800,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 2999,
        product_quantity: 45,
        product_min_quantity: 15,
        product_sku: "CLO-MEN-ADI-001",
        is_active: true,
    },

    // Clothing - Women's Wear
    {
        product_category: "Clothing",
        product_sub_category: "Women's Wear",
        product_name: "Zara Floral Dress",
        product_brand: "Zara",
        product_category_lower: "clothing",
        product_sub_category_lower: "women's wear",
        product_brand_lower: "zara",
        product_name_lower: "zara floral dress",
        product_image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
        product_cost_price: 1500,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 2499,
        product_quantity: 55,
        product_min_quantity: 15,
        product_sku: "CLO-WOM-ZAR-001",
        is_active: true,
    },
    {
        product_category: "Clothing",
        product_sub_category: "Women's Wear",
        product_name: "H&M Casual Top",
        product_brand: "H&M",
        product_category_lower: "clothing",
        product_sub_category_lower: "women's wear",
        product_brand_lower: "h&m",
        product_name_lower: "h&m casual top",
        product_image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=400",
        product_cost_price: 600,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 999,
        product_quantity: 90,
        product_min_quantity: 25,
        product_sku: "CLO-WOM-HM-001",
        is_active: true,
    },
    {
        product_category: "Clothing",
        product_sub_category: "Women's Wear",
        product_name: "Forever 21 Jeans",
        product_brand: "Forever 21",
        product_category_lower: "clothing",
        product_sub_category_lower: "women's wear",
        product_brand_lower: "forever 21",
        product_name_lower: "forever 21 jeans",
        product_image: "https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=400",
        product_cost_price: 1200,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 1899,
        product_quantity: 70,
        product_min_quantity: 20,
        product_sku: "CLO-WOM-FOR-001",
        is_active: true,
    },

    // Clothing - Footwear
    {
        product_category: "Clothing",
        product_sub_category: "Footwear",
        product_name: "Nike Air Max 270",
        product_brand: "Nike",
        product_category_lower: "clothing",
        product_sub_category_lower: "footwear",
        product_brand_lower: "nike",
        product_name_lower: "nike air max 270",
        product_image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        product_cost_price: 7000,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 12995,
        product_quantity: 40,
        product_min_quantity: 10,
        product_sku: "CLO-FOO-NIK-001",
        is_active: true,
    },
    {
        product_category: "Clothing",
        product_sub_category: "Footwear",
        product_name: "Adidas Ultraboost 23",
        product_brand: "Adidas",
        product_category_lower: "clothing",
        product_sub_category_lower: "footwear",
        product_brand_lower: "adidas",
        product_name_lower: "adidas ultraboost 23",
        product_image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
        product_cost_price: 9000,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 16999,
        product_quantity: 35,
        product_min_quantity: 10,
        product_sku: "CLO-FOO-ADI-001",
        is_active: true,
    },
    {
        product_category: "Clothing",
        product_sub_category: "Footwear",
        product_name: "Puma RS-X Sneakers",
        product_brand: "Puma",
        product_category_lower: "clothing",
        product_sub_category_lower: "footwear",
        product_brand_lower: "puma",
        product_name_lower: "puma rs-x sneakers",
        product_image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
        product_cost_price: 4500,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 7999,
        product_quantity: 2,
        product_min_quantity: 8,
        product_sku: "CLO-FOO-PUM-001",
        is_active: true,
    },

    // Home & Kitchen - Appliances
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Appliances",
        product_name: "LG 260L Refrigerator",
        product_brand: "LG",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "appliances",
        product_brand_lower: "lg",
        product_name_lower: "lg 260l refrigerator",
        product_image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400",
        product_cost_price: 18000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 25990,
        product_quantity: 15,
        product_min_quantity: 5,
        product_sku: "HOM-APP-LG-001",
        is_active: true,
    },
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Appliances",
        product_name: "Samsung Microwave Oven",
        product_brand: "Samsung",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "appliances",
        product_brand_lower: "samsung",
        product_name_lower: "samsung microwave oven",
        product_image: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=400",
        product_cost_price: 6000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 8999,
        product_quantity: 25,
        product_min_quantity: 8,
        product_sku: "HOM-APP-SAM-001",
        is_active: true,
    },
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Appliances",
        product_name: "Philips Air Fryer",
        product_brand: "Philips",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "appliances",
        product_brand_lower: "philips",
        product_name_lower: "philips air fryer",
        product_image: "https://images.unsplash.com/photo-1631656251226-4e11e277a6d7?w=400",
        product_cost_price: 4500,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 7499,
        product_quantity: 30,
        product_min_quantity: 10,
        product_sku: "HOM-APP-PHI-001",
        is_active: true,
    },

    // Home & Kitchen - Cookware
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Cookware",
        product_name: "Prestige Non-Stick Kadai",
        product_brand: "Prestige",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "cookware",
        product_brand_lower: "prestige",
        product_name_lower: "prestige non-stick kadai",
        product_image: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=400",
        product_cost_price: 800,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 1299,
        product_quantity: 100,
        product_min_quantity: 20,
        product_sku: "HOM-COO-PRE-001",
        is_active: true,
    },
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Cookware",
        product_name: "Hawkins Pressure Cooker 5L",
        product_brand: "Hawkins",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "cookware",
        product_brand_lower: "hawkins",
        product_name_lower: "hawkins pressure cooker 5l",
        product_image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
        product_cost_price: 1800,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 2799,
        product_quantity: 50,
        product_min_quantity: 15,
        product_sku: "HOM-COO-HAW-001",
        is_active: true,
    },
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Cookware",
        product_name: "Milton Steel Tiffin Set",
        product_brand: "Milton",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "cookware",
        product_brand_lower: "milton",
        product_name_lower: "milton steel tiffin set",
        product_image: "https://images.unsplash.com/photo-1584990347449-39b34c85d1e3?w=400",
        product_cost_price: 350,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 599,
        product_quantity: 75,
        product_min_quantity: 20,
        product_sku: "HOM-COO-MIL-001",
        is_active: true,
    },

    // Home & Kitchen - Furniture
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Furniture",
        product_name: "IKEA Office Chair",
        product_brand: "IKEA",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "furniture",
        product_brand_lower: "ikea",
        product_name_lower: "ikea office chair",
        product_image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400",
        product_cost_price: 5000,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 7999,
        product_quantity: 20,
        product_min_quantity: 5,
        product_sku: "HOM-FUR-IKE-001",
        is_active: true,
    },
    {
        product_category: "Home & Kitchen",
        product_sub_category: "Furniture",
        product_name: "Nilkamal Plastic Table",
        product_brand: "Nilkamal",
        product_category_lower: "home & kitchen",
        product_sub_category_lower: "furniture",
        product_brand_lower: "nilkamal",
        product_name_lower: "nilkamal plastic table",
        product_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
        product_cost_price: 1200,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 1999,
        product_quantity: 30,
        product_min_quantity: 10,
        product_sku: "HOM-FUR-NIL-001",
        is_active: true,
    },

    // Sports & Fitness - Gym Equipment
    {
        product_category: "Sports & Fitness",
        product_sub_category: "Gym Equipment",
        product_name: "Cosco Adjustable Dumbbells 10kg",
        product_brand: "Cosco",
        product_category_lower: "sports & fitness",
        product_sub_category_lower: "gym equipment",
        product_brand_lower: "cosco",
        product_name_lower: "cosco adjustable dumbbells 10kg",
        product_image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
        product_cost_price: 800,
        product_unit: "set",
        product_tax: 12,
        product_selling_price: 1299,
        product_quantity: 40,
        product_min_quantity: 10,
        product_sku: "SPO-GYM-COS-001",
        is_active: true,
    },
    {
        product_category: "Sports & Fitness",
        product_sub_category: "Gym Equipment",
        product_name: "Strauss Yoga Mat",
        product_brand: "Strauss",
        product_category_lower: "sports & fitness",
        product_sub_category_lower: "gym equipment",
        product_brand_lower: "strauss",
        product_name_lower: "strauss yoga mat",
        product_image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400",
        product_cost_price: 400,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 799,
        product_quantity: 60,
        product_min_quantity: 15,
        product_sku: "SPO-GYM-STR-001",
        is_active: true,
    },
    {
        product_category: "Sports & Fitness",
        product_sub_category: "Gym Equipment",
        product_name: "Fitbit Resistance Bands Set",
        product_brand: "Fitbit",
        product_category_lower: "sports & fitness",
        product_sub_category_lower: "gym equipment",
        product_brand_lower: "fitbit",
        product_name_lower: "fitbit resistance bands set",
        product_image: "https://images.unsplash.com/photo-1598632640487-6ea4a4e8b963?w=400",
        product_cost_price: 300,
        product_unit: "set",
        product_tax: 12,
        product_selling_price: 599,
        product_quantity: 50,
        product_min_quantity: 15,
        product_sku: "SPO-GYM-FIT-001",
        is_active: true,
    },

    // Sports & Fitness - Outdoor Sports
    {
        product_category: "Sports & Fitness",
        product_sub_category: "Outdoor Sports",
        product_name: "Nivia Storm Football Size 5",
        product_brand: "Nivia",
        product_category_lower: "sports & fitness",
        product_sub_category_lower: "outdoor sports",
        product_brand_lower: "nivia",
        product_name_lower: "nivia storm football size 5",
        product_image: "https://images.unsplash.com/photo-1614632537197-38a17061c2bd?w=400",
        product_cost_price: 350,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 699,
        product_quantity: 80,
        product_min_quantity: 20,
        product_sku: "SPO-OUT-NIV-001",
        is_active: true,
    },
    {
        product_category: "Sports & Fitness",
        product_sub_category: "Outdoor Sports",
        product_name: "Yonex Badminton Racket",
        product_brand: "Yonex",
        product_category_lower: "sports & fitness",
        product_sub_category_lower: "outdoor sports",
        product_brand_lower: "yonex",
        product_name_lower: "yonex badminton racket",
        product_image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400",
        product_cost_price: 1200,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 1999,
        product_quantity: 45,
        product_min_quantity: 12,
        product_sku: "SPO-OUT-YON-001",
        is_active: true,
    },
    {
        product_category: "Sports & Fitness",
        product_sub_category: "Outdoor Sports",
        product_name: "Wilson Tennis Ball Can",
        product_brand: "Wilson",
        product_category_lower: "sports & fitness",
        product_sub_category_lower: "outdoor sports",
        product_brand_lower: "wilson",
        product_name_lower: "wilson tennis ball can",
        product_image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400",
        product_cost_price: 200,
        product_unit: "can",
        product_tax: 12,
        product_selling_price: 399,
        product_quantity: 100,
        product_min_quantity: 25,
        product_sku: "SPO-OUT-WIL-001",
        is_active: true,
    },

    // Books & Media - Fiction
    {
        product_category: "Books & Media",
        product_sub_category: "Fiction",
        product_name: "The Great Gatsby",
        product_brand: "Penguin",
        product_category_lower: "books & media",
        product_sub_category_lower: "fiction",
        product_brand_lower: "penguin",
        product_name_lower: "the great gatsby",
        product_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        product_cost_price: 150,
        product_unit: "pcs",
        product_tax: 0,
        product_selling_price: 299,
        product_quantity: 120,
        product_min_quantity: 30,
        product_sku: "BOO-FIC-PEN-001",
        is_active: true,
    },
    {
        product_category: "Books & Media",
        product_sub_category: "Fiction",
        product_name: "Harry Potter Complete Set",
        product_brand: "Scholastic",
        product_category_lower: "books & media",
        product_sub_category_lower: "fiction",
        product_brand_lower: "scholastic",
        product_name_lower: "harry potter complete set",
        product_image: "https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=400",
        product_cost_price: 2500,
        product_unit: "set",
        product_tax: 0,
        product_selling_price: 4999,
        product_quantity: 30,
        product_min_quantity: 8,
        product_sku: "BOO-FIC-SCH-001",
        is_active: true,
    },

    // Books & Media - Non-Fiction
    {
        product_category: "Books & Media",
        product_sub_category: "Non-Fiction",
        product_name: "Atomic Habits",
        product_brand: "Random House",
        product_category_lower: "books & media",
        product_sub_category_lower: "non-fiction",
        product_brand_lower: "random house",
        product_name_lower: "atomic habits",
        product_image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
        product_cost_price: 250,
        product_unit: "pcs",
        product_tax: 0,
        product_selling_price: 499,
        product_quantity: 90,
        product_min_quantity: 20,
        product_sku: "BOO-NON-RAN-001",
        is_active: true,
    },
    {
        product_category: "Books & Media",
        product_sub_category: "Non-Fiction",
        product_name: "Rich Dad Poor Dad",
        product_brand: "Plata Publishing",
        product_category_lower: "books & media",
        product_sub_category_lower: "non-fiction",
        product_brand_lower: "plata publishing",
        product_name_lower: "rich dad poor dad",
        product_image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400",
        product_cost_price: 200,
        product_unit: "pcs",
        product_tax: 0,
        product_selling_price: 399,
        product_quantity: 110,
        product_min_quantity: 25,
        product_sku: "BOO-NON-PLA-001",
        is_active: true,
    },

    // Grocery - Snacks
    {
        product_category: "Grocery",
        product_sub_category: "Snacks",
        product_name: "Lay's Classic Salted 52g",
        product_brand: "Lay's",
        product_category_lower: "grocery",
        product_sub_category_lower: "snacks",
        product_brand_lower: "lay's",
        product_name_lower: "lay's classic salted 52g",
        product_image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400",
        product_cost_price: 15,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 20,
        product_quantity: 500,
        product_min_quantity: 100,
        product_sku: "GRO-SNA-LAY-001",
        is_active: true,
    },
    {
        product_category: "Grocery",
        product_sub_category: "Snacks",
        product_name: "Haldiram's Bhujia 400g",
        product_brand: "Haldiram's",
        product_category_lower: "grocery",
        product_sub_category_lower: "snacks",
        product_brand_lower: "haldiram's",
        product_name_lower: "haldiram's bhujia 400g",
        product_image: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400",
        product_cost_price: 80,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 120,
        product_quantity: 200,
        product_min_quantity: 50,
        product_sku: "GRO-SNA-HAL-001",
        is_active: true,
    },
    {
        product_category: "Grocery",
        product_sub_category: "Snacks",
        product_name: "Britannia Good Day Cookies",
        product_brand: "Britannia",
        product_category_lower: "grocery",
        product_sub_category_lower: "snacks",
        product_brand_lower: "britannia",
        product_name_lower: "britannia good day cookies",
        product_image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400",
        product_cost_price: 25,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 35,
        product_quantity: 300,
        product_min_quantity: 80,
        product_sku: "GRO-SNA-BRI-001",
        is_active: true,
    },

    // Grocery - Beverages
    {
        product_category: "Grocery",
        product_sub_category: "Beverages",
        product_name: "Coca Cola 1L",
        product_brand: "Coca Cola",
        product_category_lower: "grocery",
        product_sub_category_lower: "beverages",
        product_brand_lower: "coca cola",
        product_name_lower: "coca cola 1l",
        product_image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400",
        product_cost_price: 35,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 50,
        product_quantity: 250,
        product_min_quantity: 60,
        product_sku: "GRO-BEV-COC-001",
        is_active: true,
    },
    {
        product_category: "Grocery",
        product_sub_category: "Beverages",
        product_name: "Red Bull Energy Drink 250ml",
        product_brand: "Red Bull",
        product_category_lower: "grocery",
        product_sub_category_lower: "beverages",
        product_brand_lower: "red bull",
        product_name_lower: "red bull energy drink 250ml",
        product_image: "https://images.unsplash.com/photo-1622543925917-763c34f3868b?w=400",
        product_cost_price: 80,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 125,
        product_quantity: 150,
        product_min_quantity: 40,
        product_sku: "GRO-BEV-RED-001",
        is_active: true,
    },
    {
        product_category: "Grocery",
        product_sub_category: "Beverages",
        product_name: "Tropicana Orange Juice 1L",
        product_brand: "Tropicana",
        product_category_lower: "grocery",
        product_sub_category_lower: "beverages",
        product_brand_lower: "tropicana",
        product_name_lower: "tropicana orange juice 1l",
        product_image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400",
        product_cost_price: 70,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 110,
        product_quantity: 180,
        product_min_quantity: 45,
        product_sku: "GRO-BEV-TRO-001",
        is_active: true,
    },

    // Toys - Action Figures
    {
        product_category: "Toys",
        product_sub_category: "Action Figures",
        product_name: "Marvel Spider-Man Figure",
        product_brand: "Hasbro",
        product_category_lower: "toys",
        product_sub_category_lower: "action figures",
        product_brand_lower: "hasbro",
        product_name_lower: "marvel spider-man figure",
        product_image: "https://images.unsplash.com/photo-1594912837066-f41a8e023e74?w=400",
        product_cost_price: 800,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 1499,
        product_quantity: 50,
        product_min_quantity: 12,
        product_sku: "TOY-ACT-HAS-001",
        is_active: true,
    },
    {
        product_category: "Toys",
        product_sub_category: "Action Figures",
        product_name: "LEGO Star Wars Set",
        product_brand: "LEGO",
        product_category_lower: "toys",
        product_sub_category_lower: "action figures",
        product_brand_lower: "lego",
        product_name_lower: "lego star wars set",
        product_image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        product_cost_price: 2000,
        product_unit: "set",
        product_tax: 12,
        product_selling_price: 3999,
        product_quantity: 25,
        product_min_quantity: 8,
        product_sku: "TOY-ACT-LEG-001",
        is_active: true,
    },

    // Toys - Board Games
    {
        product_category: "Toys",
        product_sub_category: "Board Games",
        product_name: "Monopoly Classic",
        product_brand: "Funskool",
        product_category_lower: "toys",
        product_sub_category_lower: "board games",
        product_brand_lower: "funskool",
        product_name_lower: "monopoly classic",
        product_image: "https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=400",
        product_cost_price: 600,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 999,
        product_quantity: 40,
        product_min_quantity: 10,
        product_sku: "TOY-BOA-FUN-001",
        is_active: true,
    },
    {
        product_category: "Toys",
        product_sub_category: "Board Games",
        product_name: "Chess Board Wooden",
        product_brand: "Chessbazaar",
        product_category_lower: "toys",
        product_sub_category_lower: "board games",
        product_brand_lower: "chessbazaar",
        product_name_lower: "chess board wooden",
        product_image: "https://images.unsplash.com/photo-1586165368502-1bad197a6461?w=400",
        product_cost_price: 1200,
        product_unit: "pcs",
        product_tax: 12,
        product_selling_price: 1999,
        product_quantity: 30,
        product_min_quantity: 8,
        product_sku: "TOY-BOA-CHE-001",
        is_active: true,
    },

    // Automotive - Accessories
    {
        product_category: "Automotive",
        product_sub_category: "Accessories",
        product_name: "Car Phone Holder",
        product_brand: "Mi",
        product_category_lower: "automotive",
        product_sub_category_lower: "accessories",
        product_brand_lower: "mi",
        product_name_lower: "car phone holder",
        product_image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400",
        product_cost_price: 200,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 399,
        product_quantity: 100,
        product_min_quantity: 25,
        product_sku: "AUT-ACC-MI-001",
        is_active: true,
    },
    {
        product_category: "Automotive",
        product_sub_category: "Accessories",
        product_name: "Car Air Freshener",
        product_brand: "Ambi Pur",
        product_category_lower: "automotive",
        product_sub_category_lower: "accessories",
        product_brand_lower: "ambi pur",
        product_name_lower: "car air freshener",
        product_image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400",
        product_cost_price: 80,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 149,
        product_quantity: 200,
        product_min_quantity: 50,
        product_sku: "AUT-ACC-AMB-001",
        is_active: true,
    },

    // Automotive - Maintenance
    {
        product_category: "Automotive",
        product_sub_category: "Maintenance",
        product_name: "Engine Oil 5W-30 4L",
        product_brand: "Castrol",
        product_category_lower: "automotive",
        product_sub_category_lower: "maintenance",
        product_brand_lower: "castrol",
        product_name_lower: "engine oil 5w-30 4l",
        product_image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400",
        product_cost_price: 1500,
        product_unit: "pcs",
        product_tax: 18,
        product_selling_price: 2499,
        product_quantity: 60,
        product_min_quantity: 15,
        product_sku: "AUT-MAI-CAS-001",
        is_active: true,
    },
];

const seedDatabase = async () => {
    try {
        // Connect to database
        await connectDB();

        console.log("\n🗑️  Clearing existing products...");
        await Product.deleteMany({});
        console.log("✅ Existing products cleared");

        console.log("\n📦 Inserting products...");
        const result = await Product.insertMany(products);
        console.log(`✅ Successfully added ${result.length} products to database`);

        console.log("\n📊 Summary:");
        const categories = await Product.distinct("product_category");
        console.log(`   Categories: ${categories.length}`);

        for (const category of categories) {
            const subcategories = await Product.distinct("product_sub_category", {
                product_category: category,
            });
            console.log(`   - ${category}: ${subcategories.length} subcategories`);
        }

        console.log("\n🎉 Database seeding completed successfully!");
        process.exit(0);
    } catch (error) {
        console.error("\n❌ Error seeding database:", error);
        process.exit(1);
    }
};

// Run the seeder
seedDatabase();
